/** Walk Before Me Journey design tokens (Modern Artifact spec, modern_artifact/DESIGN.md).
 *  Source of truth for color, type roles, spacing and shape. Do not hardcode hex values in components. */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#131410',
        'surface-dim': '#131410',
        'surface-bright': '#3a3935',
        'surface-container-lowest': '#0e0e0b',
        'surface-container-low': '#1c1c18',
        'surface-container': '#20201c',
        'surface-container-high': '#2a2a26',
        'surface-container-highest': '#353530',
        'surface-variant': '#353530',
        'on-surface': '#e5e2db',
        'on-surface-variant': '#c4c6cf',
        outline: '#8e9198',
        'outline-variant': '#43474e',
        primary: '#afc8f0',
        'on-primary': '#163152',
        'primary-container': '#001f3f',
        'on-primary-container': '#6f88ad',
        secondary: '#e9c349',
        'on-secondary': '#3c2f00',
        'secondary-container': '#af8d11',
        'on-secondary-container': '#342800',
        tertiary: '#c8c6c5',
        error: '#ffb4ab',
        'error-container': '#93000a',
        navy: '#001f3f',
        gold: '#d4af37',
        parchment: '#f4f1ea',
        'parchment-ink': '#e5e2db',
        // Prophetic Blueprint accents (Zechariah 4 track)
        'radiant-amber': '#ffbf00',
        'visionary-olive': '#556b2f',
        'midnight-void': '#000b1a',
      },
      fontFamily: {
        chrome: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        narrative: ['"EB Garamond"', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['20px', { lineHeight: '1.6' }],
        'body-md': ['18px', { lineHeight: '1.6' }],
        scripture: ['22px', { lineHeight: '1.5' }],
        'label-technical': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        citation: ['14px', { lineHeight: '1', fontWeight: '600' }],
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'scripture-indent': '32px',
        sidebar: '300px',
      },
      maxWidth: { container: '1200px' },
      borderRadius: { DEFAULT: '0px', sm: '0px', md: '0px', lg: '0px', xl: '0px', full: '9999px' },
      boxShadow: { DEFAULT: 'none', md: 'none', lg: 'none' },
    },
  },
  plugins: [],
};
